# Generated by Django 4.0.3 on 2022-05-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='img',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='num_plays',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
